---
title: "Kvartalsrapport for CP-register"
output:
  pdf_document: default
  html_document: default
  word_document: default
date: '`r format(Sys.Date(), "%d %b %Y")`'
---


```{r valg, echo=FALSE, warning=FALSE, include=FALSE, message=FALSE}
rm(list = ls())

##########################
## Valg interval for år ##
##########################
aarFra <- 1996
aarTil <- 2010


```
    

```{r setup , echo=FALSE, warning=FALSE, include=FALSE, message=FALSE} 
## henter pakker eller installere om ikke finnes
inspak <- function(pkg){
  nypkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(nypkg))
    install.packages(nypkg, dependencies = TRUE, repos = "http://cran.r-project.org")
}

pakke <- c("rreg", "data.table", "ggplot2", "directlabels", "grid", "knitr", "kableExtra")
inspak(pakke)

## Upload libraries
library(rreg)
library(data.table)
library(ggplot2)
library(directlabels)
library(knitr)
library(grid)
library(kableExtra)

############
############
## DATA
filDir <- getwd()
sr01 <- paste0(filDir,"/", "datakilder1.R")
sr02 <- paste0(filDir, "/", "datakilder2.R")
##ifelse(file.exists(sr01), source(sr01), source(sr02))
data <- ifelse(file.exists(sr01), sr01, sr02)
source(data)
source(paste0(filDir, "/", "rregbar.R"))

#############
## Knitr opt
#############

knitr::opts_chunk$set(fig.path = 'figures/cp-') #mappe for figurer

##############
## Output doc
##############

## outDoc <- knitr::opts_knit$git("rmarkdown.pandoc.to") #doc type output html,latex eller docx

getOutputFormat <- function() {
  output <- rmarkdown:::parse_yaml_front_matter(
    readLines(knitr::current_input())
  )$output
  if (is.list(output)){
    return(names(output)[1])
  } else {
    return(output[1])
  }
}

printDoc <- getOutputFormat() #finne ut document type output

###########
## FARGER
###########
ColPoint <- "#FF3333" #farge for point
cols <- c("#C6DBEF", "#4292C6", "#084594") #farge for flere bar
colb <- "#99CCFF" #farge for en søyle
options(digits = 3)

###########
## Function
###########

## bytt NA med 0
bNA <- function(DT, na = 0){
  for (j in seq_len(ncol(DT)))
    set(DT,which(is.na(DT[[j]])),j, na) 
}

```

\centerline{Valgt år er fra `r aarFra` til `r aarTil`}


# Antall 5-år registreringsskjemaer

## Antall per habiliteringstjeneste

```{r habilt, echo=FALSE, warning=FALSE, message=FALSE}

setDT(cpdata) #dataset
setDT(cphab)  #navn til habiliteringstjenester

## kombinere data og hb-navn
cpdata <- merge(cpdata, cphab, by.x = "HAB_TJENESTE", by.y = "id")

## subset data ift. valg år interval
valgYear <- aarFra:aarTil
cpdata <- cpdata[FAAR %in% valgYear]


## key1 for "per habiliteringstjeneste" 
key1 <- "navn"
perhab <- cpdata[, .N, by = list("Habiliteringstjeneste" = get(key1))]

knitr::kable(perhab)
```

## Antall per fødselsår

```{r birth, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

## key2 for "per fødselsår"
key2 <- "FAAR"
peraar <- cpdata[, .N, by = get(key2)]
peraar$ant <- "Antall"

## Tabell alternativ 2
peryr <- cpdata[, .N, by = list(get(key2))]
setorder(peryr, get)

## del tabell til to
del <- (round(dim(peryr)[1] / 2))
mdel <- dim(peryr)[1]
tab3 <- peryr[1:del, ]
tab4 <- peryr[(del + 1):mdel, ]

## gir nytt navn
names(tab3)[1] <- "Fødselsår"
names(tab4)[1] <- "Fødselsår"

t1 <- kable(tab3, format = 'latex', align = c("c", "r"))
t2 <- kable(tab4, format = 'latex', align = c("c", "r"))

## knitr::kable(list(tab3, tab4), align = "crcr")

cat(c("\\begin{table}[h]
     \\centering",
     t1,
     "\\hspace{1cm}
      \\centering",
     t2,
     "\\end{table}"))

```  

\pagebreak

## Antall missing

```{r missingloc , echo=FALSE, warning=FALSE, include=FALSE, message=FALSE} 

Sys.setlocale(locale = "C")
miss <- grep("^Mangler", colnames(cpdata), value = TRUE)

tbmiss <- cpdata[, .N, by = get(miss)]

Sys.setlocale(category = "LC_ALL", locale = "")

```

```{r missing , echo=FALSE, warning=FALSE, message=FALSE} 
tbmiss$get <- factor(tbmiss$get, levels = c(0, 1), labels = c("Nei", "Ja"))
names(tbmiss)[1] <- "Mangler 5 år"

knitr::kable(tbmiss)
```

# Andel kompletthet av data 

```{r komplett, echo=FALSE, warning=FALSE, message=FALSE, fig.height=6, fig.width=7}
##total pasienter
tot <- dim(cpdata)[1]

bnna <- function(DT, var){
  antall <- DT[, ifelse(is.na(get(var)), 0, 1)]
  tot <- sum(antall)
  return(tot)
}

hab <- bnna(cpdata, "HAB_TJENESTE")
faar <- bnna(cpdata, "FAAR")
a.diag <- bnna(cpdata, "ALDER_CPDIAG")
cp.diag <- bnna(cpdata, "CPDIAG")
epi <- bnna(cpdata, "EPILEPSI")
enar <- bnna(cpdata, "ERNAERING")
gast <- bnna(cpdata, "GASTROSTOMI")
gmfc <- bnna(cpdata, "GMFCS")
hors <- bnna(cpdata, "HORSELSHEM")
kog <- bnna(cpdata, "KOG_TESTRES")
macs <- bnna(cpdata, "MACS")
hjerne <- bnna(cpdata, "HJERNEMISD")
cer <- bnna(cpdata, "MR_CEREBRAL")
post <- bnna(cpdata, "POSTNEONATAL")
spise <- bnna(cpdata, "SPISEVANSK")
sprak <- bnna(cpdata, "SF_RESULT")
syns <- bnna(cpdata, "SYNSHEM")
tale <- bnna(cpdata, "TALEFNK")

tabnavn <- c("Per habiliteringstjeneste",
             "Alle validerte fødselsårene",
             "Alder ved CP diagnose",
             "CP diagnose",
             "Epilepsi",
             "Ernæring", 
             "Gastrostomi",
             "GMFCS nivå",
             "Hørselshemming",
             "Kognisjonstest resultat",
             "MACS nivå",
             "Medfødte hjernemisdannelser",
             "MR hjernen tatt",
             "Postneonatal CP",
             "Spisevansker",
             "Språkforståelse",
             "Synshemming",
             "Talefunksjon")


tabkom <- data.table(n = c(hab, faar, a.diag, cp.diag, epi, enar, gast, gmfc,
                           hors, kog, macs, hjerne, cer, post, spise, sprak,
                           syns, tale),
                     var = tabnavn)

tabkom[, pros := round((n / tot) * 100)]

figlab <- sprintf("prosent kompletthet (N=%s)", tot)

rreg::regbar(tabkom, var, pros, num = n, ylab = figlab)


```
